[profile.default]
optimizer_runs = 1000000
remappings = [
  "@manifoldxyz/=lib/",
  "manifoldxyz/=lib/royalty-registry-solidity/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "create3-factory/=lib/create3-factory/src/",
  "solmate/=lib/solmate/src/",
  "@prb/math/=lib/prb-math/src/",
  "clones-with-immutable-args/=lib/clones-with-immutable-args/src/",
  "ds-test/=lib/clones-with-immutable-args/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
]
verbosity = 1
auto_detect_remappings = false

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_KEY}"}
